services:
  app:
    build:
      context: .
      target: development
    environment:
      LIT_GOBI_PASSWORD: "${LIT_GOBI_PASSWORD}"
      LIT_GOBI_USERNAME: "${LIT_GOBI_USERNAME}"
      LIT_LBNL_KEY_DATA: "${LIT_LBNL_KEY_DATA}"
      LIT_LBNL_USERNAME: "${LIT_LBNL_USERNAME}"
      LBNL_FILENAME: "${LBNL_FILENAME}"
    init: true 
    volumes:
      - ./:/opt/app
