services:
  app:
    build:
      context: .
      target: development
    environment:
      LIT_GOBI_PASSWORD: "${LIT_GOBI_PASSWORD}"
      LIT_LBNL_KEY_DATA: "${LIT_LBNL_KEY_DATA}"
    image: containers.lib.berkeley.edu/lap/gobi_sftp/development:latest
    init: yes
    volumes:
      - ./:/opt/app

version: "3.8"
